name: CI
on: [pull_request]
jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Instalando Dependências
        run: yarn install
      - name: Rodando Testes
        run: yarn test:ci
